### ISSUE TITLE
Error pop out in Blender when I click "Import earth studio" button

### ISSUE THREAD

**Issue by wmrlakmal** [imagiscope/EarthStudioTools#11]
Hi,
I'm getting the following error when I click "Import earth studio" button. Please let me know if you have a solution for this.

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\GES_Panel_1_2.py", line 383, in execute
    importges()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\GES_Panel_1_2.py", line 461, in importges
    s_end = camdata["numFrames"]
KeyError: 'numFrames'

location: <unknown location>:-1

**Comment by imagiscope** [comment]
This is usually because you don't have an anchor point (trackpoint) in the project. Just add one to GES project and it will become the center of the project and should import.

**Comment by wmrlakmal** [comment]
Thank you very much for the message.
