### ISSUE TITLE
unable to import earth studio with earthstudiotools 1.2 into blender

### ISSUE THREAD

**Issue by skimtiyaz** [imagiscope/EarthStudioTools#26]
Python: Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\GES_Panel_1_2.py", line 383, in execute
    importges()
  File "C:\Users\Hp\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\GES_Panel_1_2.py", line 584, in importges
    cam.parent = ges_parent
UnboundLocalError: local variable 'ges_parent' referenced before assignment

**Comment by imagiscope** [comment]
You'll need to make sure you have at least one trackpoint in the ges file
